# Generated by Django 5.1.4 on 2025-01-15 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KBK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='KOSGU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Limit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remaining_limit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('year', models.PositiveIntegerField(default=2025)),
                ('kbk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='limits', to='limits.kbk')),
                ('kosgu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='limits', to='limits.kosgu')),
            ],
        ),
    ]
