# Generated by Django 5.0.4 on 2024-09-24 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Limit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_name', models.CharField(max_length=500, verbose_name='Наименование объекта закупки')),
                ('contract_date', models.DateField(verbose_name='Дата контракта')),
                ('contract_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма контракта')),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='limit', to='contracts.contract', verbose_name='Контракт')),
            ],
        ),
    ]
