# Generated by Django 5.0.4 on 2024-09-26 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limit',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
