# Generated by Django 5.1.4 on 2025-01-11 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limit',
            name='year',
            field=models.PositiveIntegerField(default=2025),
        ),
    ]
