# Generated by Django 5.1.4 on 2025-01-12 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limits', '0002_alter_limit_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limit',
            name='kbk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='limits', to='limits.kbk'),
        ),
        migrations.AlterField(
            model_name='limit',
            name='kosgu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='limits', to='limits.kosgu'),
        ),
    ]
