# Generated by Django 5.1.4 on 2025-01-12 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limits', '0003_alter_limit_kbk_alter_limit_kosgu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kbk',
            name='code',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='kosgu',
            name='code',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
