# Generated by Django 5.1.4 on 2025-01-25 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lib_ccportal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(max_length=255, verbose_name='Поставщик (Исполнитель, подрядчик)')),
                ('contract_subject', models.CharField(max_length=500, verbose_name='Предмет контракта')),
                ('contract_number', models.CharField(max_length=50, verbose_name='Номер контракта')),
                ('contract_date', models.DateField(blank=True, null=True, verbose_name='Дата контракта')),
                ('contract_duration', models.DateField(blank=True, null=True, verbose_name='Срок действия контракта')),
                ('service_start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала услуг/поставки')),
                ('service_end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания услуг/поставки')),
                ('contract_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма контракта')),
                ('payment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма оплаты')),
                ('payment_percent', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Процент оплаты')),
                ('contract_file', models.FileField(blank=True, null=True, upload_to='contracts/', verbose_name='Файл контракта')),
                ('contract_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год контрактации')),
                ('contract_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lib_ccportal.contracttype', verbose_name='Тип контракта')),
                ('kbk_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lib_ccportal.kbk', verbose_name='КБК')),
                ('kosgu_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lib_ccportal.kosgu', verbose_name='КОСГУ')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lib_ccportal.purchaseobject', verbose_name='Наименование объекта закупки')),
                ('purchase_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lib_ccportal.purchasetype', verbose_name='Тип закупки')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_issued', models.DateField(verbose_name='Дата платежного документа')),
                ('document_name', models.CharField(max_length=255, verbose_name='Наименование и номер документа')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('payment_file', models.FileField(blank=True, null=True, upload_to='payment_docs/', verbose_name='Файл платежного документа')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='contracts.contract', verbose_name='Контракт')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pp_date', models.DateField(verbose_name='Дата платежного поручения')),
                ('pp_name', models.TextField(verbose_name='Наименование платежного поручения')),
                ('pp_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Оплаченная сумма')),
                ('pp_file', models.FileField(blank=True, null=True, upload_to='payment_orders/', verbose_name='Файл платежного поручения')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_orders', to='contracts.contract', verbose_name='Контракт')),
            ],
        ),
    ]
