# Generated by Django 5.1.4 on 2025-01-20 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contract_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Год контрактации'),
        ),
    ]
