# Generated by Django 5.0.4 on 2024-04-19 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Purchase',
            new_name='Contract',
        ),
        migrations.CreateModel(
            name='PaymentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_issued', models.DateField(verbose_name='Дата платежного документа')),
                ('document_name', models.CharField(max_length=255, verbose_name='Наименование и номер документа')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='contracts.contract', verbose_name='Контракт')),
            ],
        ),
    ]
