# Generated by Django 5.0.4 on 2024-05-02 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentdocument',
            name='pp_amount',
        ),
        migrations.RemoveField(
            model_name='paymentdocument',
            name='pp_date',
        ),
        migrations.RemoveField(
            model_name='paymentdocument',
            name='pp_name',
        ),
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pp_date', models.DateField(verbose_name='Дата платежного поручения')),
                ('pp_name', models.TextField(verbose_name='Наименование платежного поручения')),
                ('pp_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Оплаченная сумма')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_orders', to='contracts.contract', verbose_name='Контракт')),
            ],
        ),
    ]
