# Generated by Django 5.0.4 on 2024-05-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentorder',
            name='pp_file',
            field=models.FileField(blank=True, null=True, upload_to='payment_orders/', verbose_name='Файл платежного поручения'),
        ),
    ]
