# Generated by Django 5.1.4 on 2025-01-31 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата соглашения')),
                ('number', models.CharField(max_length=50, verbose_name='Номер соглашения')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_agreements', to='contracts.contract')),
            ],
        ),
    ]
