# Generated by Django 5.0.4 on 2024-04-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма оплаты'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='payment_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Процент оплаты'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='purchase_type',
            field=models.CharField(choices=[('ТРУ', 'ТРУ'), ('п. 4 ч. 1 ст. 93', 'п. 4 ч. 1 ст. 93'), ('п. 5 ч. 1 ст. 93', 'п. 5 ч. 1 ст. 93'), ('п. 23 ч. 1 ст. 93', 'п. 23 ч. 1 ст. 93')], max_length=100, verbose_name='Тип закупки'),
        ),
    ]
