# Generated by Django 5.1.4 on 2025-01-31 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_additionalagreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalagreement',
            name='agreement_file',
            field=models.FileField(blank=True, null=True, upload_to='agreements/', verbose_name='Файл соглашения'),
        ),
    ]
