# Generated by Django 5.0.4 on 2024-04-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_alter_contract_payment_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='payment_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Процент оплаты'),
        ),
    ]
