# Generated by Django 5.0.4 on 2024-05-03 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_paymentdocument_payment_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата контракта'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_type',
            field=models.CharField(choices=[('ГК', 'Государственный контракт'), ('Д', 'Договор'), ('ПД', 'Платежный документ'), ('А', 'Авансовый отчет')], max_length=100, verbose_name='Тип контракта'),
        ),
    ]
