# Generated by Django 5.0.4 on 2024-05-03 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_alter_contract_contract_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_duration',
            field=models.DateField(blank=True, null=True, verbose_name='Срок действия контракта'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='service_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания услуг/поставки'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='service_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала услуг/поставки'),
        ),
    ]
