# Generated by Django 5.0.4 on 2024-05-03 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_alter_contract_contract_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_subject',
            field=models.CharField(max_length=500, verbose_name='Предмет контракта'),
        ),
    ]
